layout_spectrum: 0.3042553
name: Furniture Grid
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - url: 'https://www.behance.net/saranggujarathi'
    name: a
    type: external
color:
  brandStrength: 0.9553192
  lightness: 0.4787234
  saturation: 0.5680851
  rhythmicContrast: 0.2297872
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
typography_spectrum: 0.3978723
